version: "3.2"

#TODO RUN BEFORE
#export DOCKERHOST=$(hostname -I | awk '{print $1}')

services:
  php:
    build: './images/php/'
    volumes:
      - ./www:/var/www/
      - ./images/php/conf/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./images/php/conf/php.ini:/usr/local/etc/php/conf.d/php.override.ini
    networks:
      - backend
    extra_hosts:
      - "dockerhost:$DOCKERHOST"
#      - ./images/php/conf/composer/auth.json:/root/.composer/auth.json


  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./images/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./www/public:/var/www/public
#      - ./logs:/var/log/nginx
    links:
      - php
    networks:
      - backend
#    extra_hosts:
#      - "dockerhost:DOCKERHOST"


networks:
  backend:
    enable_ipv6: false
    driver: bridge